language: bash # "Setting the language key to bash, sh or shell is equivalent to language: minimal." (https://docs.travis-ci.com/user/languages/minimal-and-generic/#aliases)

services:
  - docker

before_install:
- docker pull seriema/retro-cloud

script:
- ./start.sh
