version: ~> 1.0 # Opt in to beta Build Config Validation https://docs.travis-ci.com/user/build-config-validation#beta-opt-in
language: shell # "Setting the language key to bash, sh or shell is equivalent to language: minimal." (https://docs.travis-ci.com/user/languages/minimal-and-generic/#aliases)
os: linux
dist: xenial

services:
    - docker

env:
    global:
        - CONTAINER_NAME="Build-$TRAVIS_BUILD_NUMBER"

# This is in global context and runs for every stage that doesn't override it.
before_install:
# Create .env
- echo "AZURE_TENANT_ID=$AZURE_TENANT_ID" | tee -a .env
- echo "AZURE_SERVICE_PRINCIPAL_USER=$AZURE_SERVICE_PRINCIPAL_USER" | tee -a .env
- echo "AZURE_SERVICE_PRINCIPAL_SECRET=$AZURE_SERVICE_PRINCIPAL_SECRET" | tee -a .env
- echo "SCREENSCRAPER_USER=$SCREENSCRAPER_USER" | tee -a .env
- echo "SCREENSCRAPER_KEY=$SCREENSCRAPER_KEY" | tee -a .env
# Start Docker
- docker pull seriema/retro-cloud:latest-amd64
- |
    docker container create \
        --cap-add SYS_ADMIN \
        --device /dev/fuse \
        --env-file .env \
        --interactive \
        --rm \
        --tty \
        --name "$CONTAINER_NAME" \
        seriema/retro-cloud:latest-amd64
- docker container start "$CONTAINER_NAME"
name: "Docker start"

# I won't be stopping the container. I need to learn more about Travis to know when it would be a
# good time (after everything is run, even if steps failed), but it also adds time to my build.
# Seems pointless as Travis will shut down the VM that's running the container anyway.

jobs:
  include:
    - stage: "Workflows"
      # This must weirdly not have a dash, otherwise an empty job is created
      script:
      - docker exec "$CONTAINER_NAME" /bin/bash -c './shared/validate-execute-permissions.sh'
      - docker exec "$CONTAINER_NAME" /bin/bash -c './shared/lint-shellcheck.sh'
      name: "bashValidation"

    - script:
      - docker exec "$CONTAINER_NAME" /bin/bash -c './docker/compose/run_tests.sh'
      name: "imageValidation"

    - script:
      - docker exec "$CONTAINER_NAME" /bin/bash -c 'echo "You have seen my face. Now you must die."'
      name: "scriptValidation"

