version: ~> 1.0 # Opt in to beta Build Config Validation https://docs.travis-ci.com/user/build-config-validation#beta-opt-in
language: shell # "Setting the language key to bash, sh or shell is equivalent to language: minimal." (https://docs.travis-ci.com/user/languages/minimal-and-generic/#aliases)
os: linux
dist: xenial

services:
- docker

env:
  global:
  - CONTAINER_NAME="Build-$TRAVIS_BUILD_NUMBER"

#
# I would prefer to have bashValidation, imageValidation, and scriptValidation running in parallel
# as they are not blocking and builds take long enough, but I haven't found a good way in Travis
# that also is visually easy to follow in the web interface. Having everything regarding
# scriptValidation in one job hides every step inside a giant console log which is impossible to
# track down what step went wrong.
#

# This is in global context and runs for every stage that doesn't override it.
before_install:
# Create .env
- echo "AZURE_TENANT_ID=$AZURE_TENANT_ID" | tee -a .env
- echo "AZURE_SERVICE_PRINCIPAL_USER=$AZURE_SERVICE_PRINCIPAL_USER" | tee -a .env
- echo "AZURE_SERVICE_PRINCIPAL_SECRET=$AZURE_SERVICE_PRINCIPAL_SECRET" | tee -a .env
- echo "SCREENSCRAPER_USER=$SCREENSCRAPER_USER" | tee -a .env
- echo "SCREENSCRAPER_KEY=$SCREENSCRAPER_KEY" | tee -a .env

# I won't be stopping the container. I need to learn more about Travis to know when it would be a
# good time (after everything is run, even if steps failed), but it also adds time to my build.
# Seems pointless as Travis will shut down the VM that's running the container anyway.

jobs:
  include:
  #############################################################################
    - stage: "Workflows"
    # Workflow: bashValidation
    # This must weirdly not have a dash, otherwise an empty job is created
      script:
      - ./lint.sh
      name: "bashValidation"

    # Workflow: imageValidation
    - script:
      # Start Docker
      # Start validation
      - ./docker/test.sh 'latest-amd64' 'seriema/retro-cloud'
      name: "imageValidation"


  #############################################################################
    # Workflow: scriptValidation
    - script:
      # Convenience scripts for Travis fold. Based on these scripts:
      # * https://github.com/spotify/ios-ci/blob/master/bin/travis_fold
      # * https://www.koszek.com/blog/2016/07/25/dealing-with-large-jobs-on-travis/
      - |
        tmpFoldName=/tmp/.travis_fold_name
        tmpFoldHeading=/tmp/.travis_fold_heading

        travis_fold() {
          local action=$1
          local name=$2
          echo -e "travis_fold:${action}:${name}"
        }

        FOLD_START() {
          local action=start
          local name=$1
          local heading="  $2  \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
          # Gray background, with Yellow text, and a lot of space (tabs) to create an extended background
          echo -en "travis_fold:${action}:${name}\r\e[40;33m${heading}\n"
          /bin/echo -n "$name" > "$tmpFoldName"
          /bin/echo -n "$heading" > "$tmpFoldHeading"
          travis_time_start
        }

        FOLD_END() {
          local exitCode=$?
          local action=end
          local name=$(cat "${tmpFoldName}")
          local heading=$(cat "${tmpFoldHeading}")
          travis_time_finish
          echo -en "travis_fold:${action}:${name}\r\e[100;30m${heading}\n"

          # If there was an error, output it after the fold so it's visible
          if [ $exitCode -ne 0 ]; then
            # Gray background, with Red text, and a lot of space (tabs) to create an extended background
            # echo -e "\e[40;31m  $name exited with $exitCode  \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
            return "$exitCode"
          fi
        }

      # Start Docker
      - FOLD_START docker_start "Start Docker"
      - |
        docker pull seriema/retro-cloud:latest-amd64 && docker container create --cap-add SYS_ADMIN --device /dev/fuse --env-file .env --interactive --rm --tty --name "$CONTAINER_NAME" --workdir /home/pi seriema/retro-cloud:latest-amd64 && docker container start "$CONTAINER_NAME"
        FOLD_END

      # Start validation
      # name: Install Retro-Cloud on RaspberryPi (Setup Azure resources)
      - FOLD_START rpi_setup "Install Retro-Cloud on RaspberryPi (Setup Azure resources)"
      - |
        docker exec "$CONTAINER_NAME" /bin/bash -euo pipefail -c " \
          curl -fOL 'https://raw.githubusercontent.com/seriema/retro-cloud/${TRAVIS_COMMIT}/raspberry-pi/download-and-run.sh' \
          && bash download-and-run.sh $TRAVIS_COMMIT $CONTAINER_NAME \
          && rm download-and-run.sh"
        FOLD_END

      # name: Install Retro-Cloud on VM
      - FOLD_START vm_setup "Install Retro-Cloud on VM"
      - |
        docker exec "$CONTAINER_NAME" /bin/bash -c "bash -i setup-vm.sh $TRAVIS_COMMIT"
        FOLD_END

      # ame: Copy a freeware ROM to VM
      - FOLD_START copy_rom "Copy a freeware ROM to VM"
      - |
        docker exec "$CONTAINER_NAME" /bin/bash -c 'bash -i ssh-vm.sh "bash -i retro-cloud-setup/dev/test-copy-rom.sh"'
        FOLD_END

      # name: Add Screenscraper.fr credentials to VM
      - FOLD_START screenscraper "Add Screenscraper.fr credentials to VM"
      - |
        docker exec "$CONTAINER_NAME" /bin/bash -c "./add-scraper-credential.sh screenscraper '$SCREENSCRAPER_USER' '$SCREENSCRAPER_KEY'"
        FOLD_END

      # name: Run scraper on VM
      - FOLD_START run_scraper "Run scraper on VM"
      - |
        docker exec "$CONTAINER_NAME" /bin/bash -c 'bash -i run-scraper.sh'
        FOLD_END

      # name: Run all tests
      - FOLD_START test "Run all tests"
      - |
        docker exec "$CONTAINER_NAME" /bin/bash -c 'retro-cloud-setup/dev/run-tests.sh'
        FOLD_END

      after_script:
      # name: Print all environments
      - FOLD_START print "Print all environments"
      - |
        docker exec "$CONTAINER_NAME" /bin/bash -c 'bash -i retro-cloud-setup/dev/print-all.sh'
        FOLD_END
      # when: always

    # - stage: "Teardown Azure resources"
    # This must weirdly not have a dash, otherwise an empty job is created
      # script:

      # name: Teardown Azure resources
      - FOLD_START az_teardown "Teardown Azure resources"
      - |
        docker exec "$CONTAINER_NAME" /bin/bash -c "cd retro-cloud-setup && bash teardown.sh '$CONTAINER_NAME'"
        FOLD_END
      # when: always

      name: "scriptValidation"
