language: bash # "Setting the language key to bash, sh or shell is equivalent to language: minimal." (https://docs.travis-ci.com/user/languages/minimal-and-generic/#aliases)

services:
  - docker

before_install:
- docker pull seriema/retro-cloud:latest
- |
    docker run \
        --cap-add SYS_ADMIN \
        --device /dev/fuse \
        --rm \
        -it \
        seriema/retro-cloud:latest

script:
- echo "How does $HOME look like?"
- ls -la "$HOME"
