jobs:
  include:
    - stage: "workflows"                # naming the Tests stage
    - script: ./bash-validation
      name: "bashValidation"            # names the first Tests stage job
    - script: ./script-validation
      name: "scriptValidation"     # names the second Tests stage job
    - script: ./image-validation
      name: "imageValidation"     # names the second Tests stage job
