jobs:
  include:
    - stage: "workflows"                # naming the Tests stage
    - script: ./unit-tests
      name: "Unit Tests"            # names the first Tests stage job
    - script: ./integration-tests
      name: "Integration Tests"     # names the second Tests stage job
    - stage: deploy
      name: "Deploy to GCP"
      script: ./deploy
