version: 2
jobs:
  infra:
    docker:
    - image: seriema/retro-cloud:develop
    shell: /bin/bash --login -eo pipefail
    working_directory: /home/pi
    steps:

    - run:
        name: Install Retro-Cloud on RaspberryPi (Setup Azure resources)
        command: |
            wget -nv "https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/raspberry-pi/download-and-run.sh"
            bash download-and-run.sh $CIRCLE_SHA1
            rm download-and-run.sh

    - run:
        name: Print RaspberryPi ~/.bashrc
        command: cat ~/.bashrc
        when: always

    - run:
        name: Print VM ~/.bashrc
        command: |
            echo 'ssh $RETROCLOUD_VM_USER@$RETROCLOUD_VM_IP "cat ~/.bashrc"' > print-vm-bashrc.sh
            bash -i print-vm-bashrc.sh
            rm print-vm-bashrc.sh
        when: always

    - run:
        name: Install Retro-Cloud on VM
        command: bash -i setup-vm.sh $CIRCLE_SHA1

    - run:
        name: Copy a freeware ROM to VM
        command: bash -i ssh-vm.sh "wget -O - -nv https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/virtual-machine/dev/test-copy-rom.sh | bash -i"

    - run:
        name: Run scraper on VM
        command: bash -i run-scraper.sh

    - run:
        name: Print RaspberryPi ~/ directory listing
        command: sudo find ~ | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
        when: always

    - run:
        name: Print VM ~/ directory listing
        command: |
            printCmd='sudo find ~ | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"'
            echo 'ssh $RETROCLOUD_VM_USER@$RETROCLOUD_VM_IP' "'$printCmd'" > print-vm-filesystem.sh
            bash -i print-vm-filesystem.sh
            rm print-vm-filesystem.sh
        when: always

    - run:
        name: Teardown Azure resources
        command: |
            wget -nv "https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/raspberry-pi/teardown.sh"
            wget -nv "https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/raspberry-pi/teardown-az.ps1"
            bash -i teardown.sh
            rm teardown.sh
            rm teardown-az.ps1
        when: always

workflows:
  version: 2
  build:
    jobs:
    - infra
