version: 2
jobs:
  build:
    docker:
    - image: seriema/retro-cloud:develop
    steps:
    - checkout
    - run: cd raspberry-pi ; bash setup.sh
workflows:
  version: 2
  build:
    jobs:
    - build
