version: 2
jobs:
  bashValidation:
    docker:
    - image: koalaman/shellcheck-alpine:stable
    steps:

    - checkout

    - run:
        name: Lint Scripts
        command: find . -type f -name '*.sh' | xargs shellcheck --external-sources

  scriptValidation:
    docker:
    - image: seriema/retro-cloud:develop
    shell: /bin/bash --login -eo pipefail
    working_directory: /home/pi
    steps:

    - run:
        name: Install Retro-Cloud on RaspberryPi (Setup Azure resources)
        command: |
            curl -OL "https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/raspberry-pi/download-and-run.sh"
            bash download-and-run.sh $CIRCLE_SHA1
            rm download-and-run.sh

    - run:
        name: Install Retro-Cloud on VM
        command: bash -i setup-vm.sh $CIRCLE_SHA1

    - run:
        name: Copy a freeware ROM to VM
        command: bash -i ssh-vm.sh "curl -L https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/virtual-machine/dev/test-copy-rom.sh | bash -i"

    - run:
        name: Add Screenscraper.fr credentials to VM
        command: |
            bash -i ssh-vm.sh "echo '' | tee -a ~/.skyscraper/config.ini"
            bash -i ssh-vm.sh "echo '[screenscraper]' | tee -a ~/.skyscraper/config.ini"
            bash -i ssh-vm.sh "echo 'userCreds=\"${SCREENSCRAPER_USER}:${SCREENSCRAPER_KEY}\"' | tee -a ~/.skyscraper/config.ini"

    - run:
        name: Run scraper on VM
        command: bash -i run-scraper.sh

    - run:
        name: Verify that ROM shows up in Azure File Share
        command: |
            curl -OL "https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/raspberry-pi/dev/test-az-share.ps1"
            echo 'pwsh -executionpolicy bypass -File ".\test-az-share.ps1"' > run-az-share-test.sh
            bash -i run-az-share-test.sh
            rm run-az-share-test.sh test-az-share.ps1

    - run:
        name: Verify scraper output on VM
        command: |
            bash -i ssh-vm.sh "mkdir -p ~/tmp"
            bash -i ssh-vm.sh "curl -L -o ~/tmp/test-gamelist.sh https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/virtual-machine/dev/test-gamelist.sh"
            bash -i ssh-vm.sh "curl -L -o ~/tmp/test-gamelist.xml https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/virtual-machine/dev/test-gamelist.xml"
            bash -i ssh-vm.sh "curl -L -o ~/tmp/test-gamelist-screenscraper-failed.xml https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/virtual-machine/dev/test-gamelist-screenscraper-failed.xml"
            bash -i ssh-vm.sh "bash -i ~/tmp/test-gamelist.sh"
            bash -i ssh-vm.sh "rm ~/tmp/test-gamelist.sh ~/tmp/test-gamelist.xml ~/tmp/test-gamelist-screenscraper-failed.xml"

    - run:
        name: Print RaspberryPi ~/.retro-cloud.env
        command: cat ~/.retro-cloud.env
        when: always

    - run:
        name: Print VM ~/.retro-cloud.env
        command: |
            echo 'ssh $RETROCLOUD_VM_USER@$RETROCLOUD_VM_IP "cat ~/.retro-cloud.env"' > print-vm-bashrc.sh
            bash -i print-vm-bashrc.sh
            rm print-vm-bashrc.sh
        when: always

    - run:
        name: Print RaspberryPi ~/.bashrc
        command: cat ~/.bashrc
        when: always

    - run:
        name: Print VM ~/.bashrc
        command: |
            echo 'ssh $RETROCLOUD_VM_USER@$RETROCLOUD_VM_IP "cat ~/.bashrc"' > print-vm-bashrc.sh
            bash -i print-vm-bashrc.sh
            rm print-vm-bashrc.sh
        when: always

    - run:
        name: Print RaspberryPi ~/ directory listing
        command: sudo find ~ | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
        when: always

    - run:
        name: Print VM ~/ directory listing
        command: |
            printCmd='sudo find ~ | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"'
            echo 'ssh $RETROCLOUD_VM_USER@$RETROCLOUD_VM_IP' "'$printCmd'" > print-vm-filesystem.sh
            bash -i print-vm-filesystem.sh
            rm print-vm-filesystem.sh
        when: always

    - run:
        name: Print Azure File Share directory listing
        command: |
            curl -OL "https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/raspberry-pi/dev/list-az-share.ps1"
            echo 'pwsh -executionpolicy bypass -File ".\list-az-share.ps1"' > run-az-listing.sh
            bash -i run-az-listing.sh
            rm run-az-listing.sh list-az-share.ps1
        when: always

    - run:
        name: Print VM Skyscraper config
        command: bash -i ssh-vm.sh "cat ~/.skyscraper/config.ini"
        when: always

    - run:
        name: Teardown Azure resources
        command: |
            curl -OL "https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/raspberry-pi/teardown.sh"
            curl -OL "https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/raspberry-pi/teardown-az.ps1"
            bash -i teardown.sh
            rm teardown.sh
            rm teardown-az.ps1
        when: always

  imageValidation:
    docker:
    - image: seriema/retro-cloud:develop
    working_directory: /home/pi/retro-cloud
    steps:

    - checkout

    - run:
        name: Validate Docker image
        command: bash docker/compose/run_tests.sh

workflows:
  version: 2
  commit:
    jobs:
    - bashValidation
    - scriptValidation
    - imageValidation
