version: 2
jobs:
  bashValidation:
    machine:
      image: ubuntu-1604:201903-01
    steps:

    - checkout

    - run:
        name: Validate scripts execution permission
        command: ./shared/validate-execute-permissions.sh

    - run:
        name: Lint Scripts
        command: ./shared/lint-shellcheck.sh

  scriptValidation:
    docker:
    - image: seriema/retro-cloud:develop
    shell: /bin/bash --login -eo pipefail
    working_directory: /home/pi
    steps:

    - run:
        name: Install Retro-Cloud on RaspberryPi (Setup Azure resources)
        command: |
            curl -fOL "https://raw.githubusercontent.com/seriema/retro-cloud/${CIRCLE_SHA1}/raspberry-pi/download-and-run.sh"
            bash download-and-run.sh $CIRCLE_SHA1
            rm download-and-run.sh

    - run:
        name: Install Retro-Cloud on VM
        command: bash -i setup-vm.sh $CIRCLE_SHA1

    - run:
        name: Copy a freeware ROM to VM
        command: bash -i ssh-vm.sh 'bash -i retro-cloud-setup/dev/test-copy-rom.sh'

    - run:
        name: Add Screenscraper.fr credentials to VM
        command: ./add-scraper-credential.sh screenscraper "$SCREENSCRAPER_USER" "$SCREENSCRAPER_KEY"

    - run:
        name: Run scraper on VM
        command: bash -i run-scraper.sh

    - run:
        name: Verify that ROM shows up in Azure File Share
        command: bash -i -c 'pwsh -executionpolicy bypass -File ".\retro-cloud-setup\dev\test-az-share.ps1"'

    - run:
        name: Verify scraper output on VM
        command: bash -i ssh-vm.sh "bash -i retro-cloud-setup/dev/test-gamelist.sh"

    - run:
        name: Print RaspberryPi ~/.retro-cloud.env
        command: cat ~/.retro-cloud.env
        when: always

    - run:
        name: Print VM ~/.retro-cloud.env
        command: bash -i ssh-vm.sh 'cat "$HOME/.retro-cloud.env"'
        when: always

    - run:
        name: Print RaspberryPi ~/.bashrc
        command: cat ~/.bashrc
        when: always

    - run:
        name: Print VM ~/.bashrc
        command: bash -i ssh-vm.sh 'cat "$HOME/.bashrc"'
        when: always

    - run:
        name: Print RaspberryPi ~/ directory listing
        command: bash -i retro-cloud-setup/dev/list-home.sh
        when: always

    - run:
        name: Print VM ~/ directory listing
        command: bash -i ssh-vm.sh "bash -i retro-cloud-setup/dev/list-home.sh"
        when: always

    - run:
        name: Print Azure File Share directory listing
        command: bash -i -c 'pwsh -executionpolicy bypass -File ".\retro-cloud-setup\dev\list-az-share.ps1"'
        when: always

    - run:
        name: Print VM Skyscraper config
        command: bash -i ssh-vm.sh "cat ~/.skyscraper/config.ini"
        when: always

    - run:
        name: Teardown Azure resources
        command: cd retro-cloud-setup && bash teardown.sh
        when: always

  imageValidation:
    docker:
    - image: seriema/retro-cloud:develop
    working_directory: /home/pi/retro-cloud
    steps:

    - checkout

    - run:
        name: Validate Docker image
        command: bash docker/compose/run_tests.sh

workflows:
  version: 2
  commit:
    jobs:
    - bashValidation
    - scriptValidation
    - imageValidation
