version: 2
jobs:
  build:
    docker:
    - image: seriema/retro-cloud:develop
    steps:
    - checkout
    # GitHub has the public key, and CircleCI adds the private key to the
    # container. RetroPie setups either have no ssh keys or both private
    # and public keys, so we remove this private key. Otherwise the scripts
    # need to change just to work with CircleCI.
    - run: sudo rm ~/.ssh/id_rsa
    - run:
        name: Setup Azure resources
        command: cd raspberry-pi ; bash setup.sh
        shell: /bin/bash --login -eo pipefail
    - run:
        name: Print ~/.bashrc
        command: cat ~/.bashrc
        shell: /bin/bash --login -eo pipefail
        when: always
    - run:
        name: Teardown Azure resources
        command: cd raspberry-pi ; bash -i teardown.sh
        shell: /bin/bash --login -eo pipefail
        when: always
workflows:
  version: 2
  build:
    jobs:
    - build
