version: 2
jobs:
  infra:
    docker:
    - image: seriema/retro-cloud:develop
    shell: /bin/bash --login -eo pipefail
    steps:

    - checkout

    - run:
        # GitHub has the public key, and CircleCI adds the private key to the
        # container. RetroPie setups either have no ssh keys or both private
        # and public keys, so we remove this private key. Otherwise the scripts
        # need to change just to work with CircleCI.
        name: Delete the private key from the "Checkout code" step above
        command: sudo rm ~/.ssh/id_rsa

    - run:
        name: Setup Azure resources
        command: cd raspberry-pi ; bash setup.sh

    - run:
        name: Print RaspberryPi ~/.bashrc
        command: cat ~/.bashrc
        when: always

    - run:
        name: Print VM ~/.bashrc
        command: |
            echo 'ssh $RETROCLOUD_VM_USER@$RETROCLOUD_VM_IP "cat ~/.bashrc"' > print-vm-bashrc.sh
            bash -i print-vm-bashrc.sh
            rm print-vm-bashrc.sh
        when: always

    - run:
        name: Setup VM
        command: bash -i raspberry-pi/local/setup-vm.sh $CIRCLE_SHA1

    - run:
        name: Teardown Azure resources
        command: cd raspberry-pi ; bash -i teardown.sh
        when: always

workflows:
  version: 2
  build:
    jobs:
    - infra
