@startuml architecture

cloud {
    node scraper_vm
    storage scraper_storage {
        storage scraper_cache
        storage scraper_media
        storage roms_storage
    }
}

node raspberry_pi

raspberry_pi <--> scraper_vm : read/write
scraper_vm <--> scraper_storage : read/write

raspberry_pi <.. scraper_media
raspberry_pi <.. roms_storage

@enduml
