@startuml filestructure

storage "retro-cloud" as scraper_share {
    folder cache {
        card "images and metadata"
    }
    folder ".emulationstation" {
        folder downloaded_media as scraper_downloadedmedia {
            folder "scummvm" as scraper_downloadedmedia_scummvm {
                folder screenshots {
                    file "bass-cd-1.2.png"
                }
            }
        }
        folder gamelists as scraper_gamelists {
            folder "scummvm" as scraper_gamelists_scummvm {
                file "gamelist.xml"
            }
        }
    }
    folder RetroPie {
        folder roms as roms_roms {
            folder "scummvm" as roms_scummvm {
                file "bass-cd-1.2.zip"
            }
        }
    }
}

node raspberry_pi {
    folder ".emulationstation" as raspberrypi_emulationstation {
        folder downloaded_media as raspberrypi_downloaded_media #BADA55
        folder gamelists as raspberrypi_gamelists #BADA55
    }
    folder RetroPie as raspberrpi_retropie {
        folder roms as raspberrypi_roms #BADA55
    }
    folder ".ssh" as raspberrypi_ssh {
        file "id_rsa.pub" as id_rsa
    }
    folder mnt as raspberrypi_mount {
        folder "[date-time stamp]__retro-cloud" as raspberrypi_scrapervm #BADA55
    }
}

node scraper_vm {
    folder ".skyscraper" as scrapervm_skyscraper {
        file "artwork.xml" as scrapervm_artwork #C0FFEE
        file "config.ini" as scrapervm_config #C0FFEE
    }
    folder ".ssh" {
        file authorized_keys
    }
    folder "retro-cloud-share" as scrapervm_mount #BADA55
}

' RASPBERRY PI
' relation
authorized_keys .. id_rsa
' mounts
raspberrypi_scrapervm <-- scrapervm_mount
' symlinks
raspberrypi_gamelists -- raspberrypi_scrapervm
raspberrypi_downloaded_media -- raspberrypi_scrapervm
raspberrypi_roms -- raspberrypi_scrapervm
' actual dependencies
raspberrypi_gamelists <.. scraper_gamelists
raspberrypi_downloaded_media <.. scraper_downloadedmedia
raspberrypi_roms <.. roms_roms

' SCRAPER VM
' mounts
scrapervm_mount <--> scraper_share

@enduml
